Improve function... (NEEDS TESTING)

diff --git a/ip-shuffle b/ip-shuffle
--- a/ip-shuffle
+++ b/ip-shuffle
@@ -100,7 +100,7 @@ generate_random_ip() {
 }
 
 ####
-# Check if the given IP address is available on the network, via a ping check.
+# Check if the given IP address is available on the network, via ICMP.
 #
 # GLOBALS:
 #   - C_INFO : Indicates an informational message to the user.
@@ -168,9 +168,14 @@ validate_network_config() {
 ####
 # Check gateway reachability.
 #
+# GLOBALS:
+#   - C_GATEWAY : The gateway IP address to check.
+#   - C_INFO : Indicates an informational message to the user.
+#   - C_ERROR : Indicates an error message to the user.
+#
 # RETURNS:
 #   - 0: If the gateway is reachable.
-#   - 1: If the gateway is not reachable.
+#   - 1: If the gateway is NOT reachable.
 check_gateway_reachability() {
     echo "${C_INFO}Checking reachability of gateway: $C_GATEWAY"
 
@@ -182,7 +187,7 @@ check_gateway_reachability() {
     return 0
 }
 
-####
+#### TODO: Test to see if the subshell properly exits and resets network on error!!!
 # Set the IP address of the network interface.
 #
 # PARAMETERS:
@@ -193,37 +198,33 @@ set_ip_address() {
 
     echo "${C_INFO}Setting IP address to '$ip' on interface '$C_INTERFACE'..."
 
-    {
+    (
+        trap '{
+            echo "${C_ERROR}An error occurred while trying to set a new IP Address." >&2
+            reset_network
+            exit 1
+        }' ERR
+
         if hash ip &>/dev/null; then
-            ip addr flush dev "$C_INTERFACE" \
-            && ip addr add "$ip"/"$C_NETMASK_CIDR" dev "$C_INTERFACE" \
-            && {
-                ip route del default \
-                || echo "${C_NOTICE}No default route to delete."
-            } \
-            && ip link set "$C_INTERFACE" up \
-            && ip route add default via "$C_GATEWAY"
+            ip addr flush dev "$C_INTERFACE"
+            ip addr add "$ip"/"$C_NETMASK_CIDR" dev "$C_INTERFACE"
+            ip route del default || echo "${C_NOTICE}No default route to delete."
+            ip link set "$C_INTERFACE" up
+            ip route add default via "$C_GATEWAY"
         else
             case $C_OS in
                 *BSD)
-                    ifconfig "$C_INTERFACE" inet "$ip" netmask "$C_NETMASK" \
-                    && {
-                        route delete default \
-                        || echo "${C_NOTICE}No default route to delete."
-                    } \
-                    && route add default "$C_GATEWAY"
+                    ifconfig "$C_INTERFACE" inet "$ip" netmask "$C_NETMASK"
+                    route delete default || echo "${C_NOTICE}No default route to delete."
+                    route add default "$C_GATEWAY"
                     ;;
                 Linux)
-                    ifconfig "$C_INTERFACE" "$ip" netmask "$C_NETMASK" \
-                    && route add default gw "$C_GATEWAY"
+                    ifconfig "$C_INTERFACE" "$ip" netmask "$C_NETMASK"
+                    route add default gw "$C_GATEWAY"
                     ;;
             esac
         fi
-    } || {
-        echo "${C_ERROR}An error occurred while trying to set a new IP Address." >&2
-        reset_network
-        clean_exit 1
-    }
+    ) || clean_exit 1
 }
 
 ####
